### ISSUE TITLE
Component does not implement a Shutdown lifecycle hook; deployments fail.

### ISSUE THREAD

**Issue by brianthelion** [awslabs/aws-greengrass-labs-containerized-secure-tunneling#6]
Unlike [other containerized components](https://github.com/awslabs/aws-greengrass-labs-openthread-border-router/blob/7ceb3b9679f34e05b52ceab8c2c81a4118ebba7b/recipe.yaml#L25-L41), this one (1) uses `Run:` instead of `Startup:` and (2) does not implement a `Shutdown:` lifecycle hook.

When combined with the use of `docker run --name`, the result is that revised Deployments fail because no two docker containers are allowed to share the same name. This throws exit code 125.

**Comment by Kriechi** [comment]
fixed by #5

**Comment by brianthelion** [comment]
@Kriechi This does not fix the issue. `Run:` should be replaced by `Startup:` and `docker run` must used `--detached`.

**Comment by Kriechi** [comment]
@brianthelion I consider Startup+detached an alternative approach.

The changes in #5 also follow a common pattern with other awslabs GG recipes: using Run + Shutdown to clean up the container if it is not auto-removed with the `--rm` flag (might happen if the container takes to long to shutdown and Nucleus decides to time-out the operation instead).
